import {PropertyPhoto} from './propertyPhoto';
import {User} from './user';

export interface Property {
  id: number;
  user_id: number;
  property_type: string;
  address: string;
  place_type: string;
  guests: number;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  pets: string;
  amenities: string;
  standout_amenities: string;
  safety_items: string;
  photos: string;
  house_title: string;
  barn: string;
  description: string;
  guest_type: string;
  price: number;
  book_faster: string;
  security_camera: string;
  weapon: string;
  animals: string;
  events: string;
  smoking: string;
  commercial_photography: string;
  quiet_hours: string;
  checkin_time: string;
  checkout_time: string;
  additional_rules: string;
  created_at: Date;
  updated_at: Date;
  min_stay: null;
  max_stay: null;
  far_booking: null;
  book_checkin_time: null;
  specific_date: null;
  cancelation_policy: null;
  long_term_cancelation_policy: null;
  status: string;
  lat: string;
  long: string;
  city: string;
  state: string;
  country: string;
  zip: string;
  combine_rate: string;
  step: string;
  wifi: null | string;
  user_details: User;
  property_photos: PropertyPhoto[];
}
