export const LOADER_TRUE = 'LOADER_TRUE';
export const LOADER_FALSE = 'LOADER_FALSE';
export const LOADING_PROGRESS = 'LOADING_PROGRESS';
export const LOADING_PROGRESS_COMPLETE = 'LOADING_PROGRESS_COMPLETE';
